/gp/controller_manager:
  ros__parameters:
    update_rate: 225  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    impedance_controller:
      type: impedance_controller/ImpedanceController

    ets_state_broadcaster:
      type: external_torque_sensor_broadcaster/ExternalTorqueSensorBroadcaster

/gp/left_arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - iiwa_left_joint_1
      - iiwa_left_joint_2
      - iiwa_left_joint_3
      - iiwa_left_joint_4
      - iiwa_left_joint_5
      - iiwa_left_joint_6
      - iiwa_left_joint_7

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

velocity_controller:
  ros__parameters:
    joints:
      - iiwa_left_joint_1
      - iiwa_left_joint_2
      - iiwa_left_joint_3
      - iiwa_left_joint_4
      - iiwa_left_joint_5
      - iiwa_left_joint_6
      - iiwa_left_joint_7

impedance_controller:
  ros__parameters:
    joints:
      - iiwa_left_joint_1
      - iiwa_left_joint_2
      - iiwa_left_joint_3
      - iiwa_left_joint_4
      - iiwa_left_joint_5
      - iiwa_left_joint_6
      - iiwa_left_joint_7
    stiffness: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0]
    damping: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]

/gp/right_arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - iiwa_right_joint_1
      - iiwa_right_joint_2
      - iiwa_right_joint_3
      - iiwa_right_joint_4
      - iiwa_right_joint_5
      - iiwa_right_joint_6
      - iiwa_right_joint_7

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

velocity_controller:
  ros__parameters:
    joints:
      - iiwa_right_joint_1
      - iiwa_right_joint_2
      - iiwa_right_joint_3
      - iiwa_right_joint_4
      - iiwa_right_joint_5
      - iiwa_right_joint_6
      - iiwa_right_joint_7

impedance_controller:
  ros__parameters:
    joints:
      - iiwa_right_joint_1
      - iiwa_right_joint_2
      - iiwa_right_joint_3
      - iiwa_right_joint_4
      - iiwa_right_joint_5
      - iiwa_right_joint_6
      - iiwa_right_joint_7
    stiffness: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0]
    damping: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
    
/gp/ets_state_broadcaster:
  ros__parameters:
    sensor_name: external_torque_sensor
