# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  joint_1: 0.174533
  joint_2: 0.349066
  joint_3: 0.0
  joint_4: -0.872665
  joint_5: 0.0
  joint_6: 0.872665
  joint_7: 0.0
