<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="generic_aruco">
  <!-- connected_to: if given the model will be connected to it -->
  <!-- aruco_l: is the x and y dimension of the black core of the code -->
  <!-- aruco_name: The link are called after this name e.g.: ${aruco_name}_link_0. -->
  <!-- 2*white_border: dimension of the white border around the marker in %. -->
  <xacro:macro name="generic_aruco" params="connected_to:='' aruco_name aruco_dictionary aruco_id aruco_l white_border *origin">
    <!-- HardwareInterface:='EffortJointInterface' -->
    <xacro:unless value="${not connected_to}">
      <joint name="${aruco_name}_joint_${connected_to}" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${aruco_name}_link_0"/>
        <xacro:insert_block name="origin"/>
      </joint>
    </xacro:unless>

    <!-- LINK 0 -->
    <link name="${aruco_name}_link_0">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0" />
        <inertia ixx="0.0741666666667" ixy="0.0" ixz="0.0" iyy="0.0585416666667" iyz="0.0" izz="0.0260416666667"/>
      </inertial>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${aruco_l} ${aruco_l} ${0.01 * aruco_l/0.09}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${aruco_l} ${aruco_l} ${0.01 * aruco_l/0.09}"/>
        </geometry>
         <material name="white">
	    <color rgba="1 1 1 1"/>
	  </material>
      </visual>
      <visual>
        <origin rpy="0.0 0 0" xyz="0 0 0"/>
        <geometry>
          <!-- <box size="0.09 0.09 0.01"/> -->
          <mesh filename="package://iiwa_description/meshes/aruco/aruco.dae" scale="${aruco_l/0.09} ${aruco_l/0.09} ${aruco_l/0.09}"/>
        </geometry>
      </visual>
    </link>
    
    <link name="${aruco_name}_link_origin" />
    
    <joint name="${aruco_name}_joint_origin_link0" type="fixed">
    <parent link = "${aruco_name}_link_0"/>
    <child link= "${aruco_name}_link_origin" />
    <origin xyz="${aruco_l/2 - white_border} ${aruco_l/2 - white_border} ${0.005 * aruco_l/0.09}" rpy="0 0 3.14"/>
    </joint>
    

    <gazebo reference="${aruco_name}_link_0">
      <kp>100000.0</kp>
      <kd>100000.0</kd>
      <mu1>0.1</mu1>
      <mu2>0.1</mu2>
      <fdir1>1 0 0</fdir1>
    </gazebo>
  </xacro:macro>
</robot>
