/**:
  ros__parameters:
    robot_description_kinematics:
      iiwa_left_arm:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.01
        kinematics_solver_timeout: 0.05
        kinematics_solver_attempts: 3
      iiwa_right_arm:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.01
        kinematics_solver_timeout: 0.05
        kinematics_solver_attempts: 3
      iiwa_left_arm_tactile:
        kinematics_solver: iiwa_left_arm_tactile/IKFastKinematicsPlugin
        kinematics_solver_search_resolution: 0.01
        kinematics_solver_timeout: 0.05
        kinematics_solver_attempts: 3
      iiwa_right_arm_tactile:
        kinematics_solver: iiwa_right_arm_tactile/IKFastKinematicsPlugin
        kinematics_solver_search_resolution: 0.01
        kinematics_solver_timeout: 0.05
        kinematics_solver_attempts: 3
