/**:
  ros__parameters:
    moveit_controller_manager:
        moveit_simple_controller_manager/MoveItSimpleControllerManager

    moveit_simple_controller_manager:
      controller_names:
        - left_arm_controller
        - right_arm_controller

      left_arm_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: true
        joints:
          - l_joint_a1
          - l_joint_a2
          - l_joint_a3
          - l_joint_a4
          - l_joint_a5
          - l_joint_a6
          - l_joint_a7

      right_arm_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: true
        joints:
          - r_joint_a1
          - r_joint_a2
          - r_joint_a3
          - r_joint_a4
          - r_joint_a5
          - r_joint_a6
          - r_joint_a7
