/**:
  ros__parameters:
    moveit_controller_manager:
        moveit_simple_controller_manager/MoveItSimpleControllerManager

    moveit_simple_controller_manager:
      controller_names:
        - left_arm_controller
        - right_arm_controller

      left_arm_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: true
        joints:
          - iiwa_left_joint_1
          - iiwa_left_joint_2
          - iiwa_left_joint_3
          - iiwa_left_joint_4
          - iiwa_left_joint_5
          - iiwa_left_joint_6
          - iiwa_left_joint_7

      right_arm_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: true
        joints:
          - iiwa_right_joint_1
          - iiwa_right_joint_2
          - iiwa_right_joint_3
          - iiwa_right_joint_4
          - iiwa_right_joint_5
          - iiwa_right_joint_6
          - iiwa_right_joint_7
